name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install ruby-build and Ruby
        run: |
          curl -sSL https://github.com/rbenv/ruby-build/archive/master.tar.gz | tar xz
          cd ruby-build-master
          sudo ./install.sh
          ruby-build 3.1.4 /opt/hostedtoolcache/Ruby/3.1.4/x64
          touch /opt/hostedtoolcache/Ruby/3.1.4/x64.complete

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build the site
        run: |
          # 你的构建命令
          bundle exec jekyll build