name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04  # 使用 GitHub-hosted runner，避免使用 self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install ruby-build and Ruby
        run: |
          # 安装 ruby-build 用于安装 Ruby
          curl -sSL https://github.com/rbenv/ruby-build/archive/master.tar.gz | tar xz
          cd ruby-build-master
          sudo ./install.sh

          # 安装 Ruby 版本 3.1.4 到指定目录
          ruby-build 3.1.4 /opt/hostedtoolcache/Ruby/3.1.4/x64

          # 标记安装完成
          touch /opt/hostedtoolcache/Ruby/3.1.4/x64.complete

      - name: Install dependencies
        run: |
          # 安装 Bundler 和其他依赖
          gem install bundler
          bundle install

      - name: Build the site
        run: |
          # 你的构建命令，例如使用 Jekyll 构建网页
          bundle exec jekyll build